CREATE TABLE IF NOT EXISTS model_settings(id INTEGER PRIMARY KEY CHECK(id=1),consent_external INTEGER NOT NULL DEFAULT 0);
INSERT INTO model_settings(id,consent_external) VALUES (1,0) ON CONFLICT(id) DO NOTHING;
CREATE TABLE IF NOT EXISTS model_jobs(batch_id TEXT PRIMARY KEY REFERENCES batches(id),status TEXT NOT NULL,processed INTEGER NOT NULL DEFAULT 0,failed INTEGER NOT NULL DEFAULT 0);
