import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1200, height: 950 } })
await p.addInitScript(() => localStorage.clear())
await p.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
await p.waitForTimeout(2500)
await p.locator('.tab').nth(2).click(); await p.waitForTimeout(400)
await p.getByRole('button', { name: 'Загрузить выписку' }).click(); await p.waitForTimeout(500)
await p.getByRole('button', { name: 'Чек или скриншот' }).click(); await p.waitForTimeout(400)
console.log('подпись:', await p.locator('.dz-note').innerText())
await p.setInputFiles('input[type=file][accept="image/*"]', 'scripts/shots/e1-home-server.png')
await p.waitForTimeout(1500)
console.log('ответ без ключа:', await p.locator('.note').first().innerText())
await p.screenshot({ path: 'scripts/shots/f6-photo-nokey.png' })
await b.close()
