import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1200, height: 950 } })
const errs = []
p.on('pageerror', e => errs.push(e.message))
await p.addInitScript(() => localStorage.clear())
await p.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
await p.waitForTimeout(2500)
await p.locator('.tab', { hasText: 'Ещё' }).first().click()
await p.getByRole('button', { name: 'Данные' }).click()
await p.waitForTimeout(500)
await p.getByRole('button', { name: 'выключена' }).click()
await p.waitForTimeout(500)
await p.getByRole('button', { name: 'Yandex Cloud' }).click()
await p.waitForTimeout(500)
const url = await p.locator('input[aria-label="Адрес API"]').inputValue()
const model = await p.locator('input[aria-label="Название модели"]').inputValue()
console.log('после выбора Yandex:')
console.log('  адрес :', url)
console.log('  модель:', model)
const notes = await p.locator('.note').allInnerTexts()
console.log('  подпись:', notes.find(n => n.includes('авторизации'))?.replace(/\s+/g,' '))
await p.evaluate(() => document.querySelector('.screen').scrollTo(0, 1100))
await p.screenshot({ path: 'scripts/shots/g1-llm-yandex.png' })
await p.getByRole('button', { name: 'OpenAI' }).click()
await p.waitForTimeout(400)
console.log('после выбора OpenAI:')
console.log('  адрес :', await p.locator('input[aria-label="Адрес API"]').inputValue())
console.log('  модель:', await p.locator('input[aria-label="Название модели"]').inputValue())
console.log(errs.length ? 'ОШИБКИ: ' + errs.join(' | ') : 'ошибок нет')
await b.close()
